### PR TITLE
add new mirror

### PR DESCRIPTION
**Pull request by jiacai2050**

### CODE REVIEW

**Comment by mlugg** [comment]
Can you confirm that your mirror follows the guidelines in the README? What're you using to host it?

**Comment by jiacai2050** [comment]
> Can you confirm that your mirror follows the guidelines in the README?

Yes, I read carefully before submit this PR.



> What're you using to host it?

`/zigbuilds` is a cloudflare [page function](https://developers.cloudflare.com/pages/functions/), and it will download requested file from ziglang.org and cache it on server if it couldn't be found in my server, so next time it will be a cache hit.
,

**Comment by mlugg** [comment]
Okay, thank you! I'll run some sanity checks shortly, and merge if all is good.

**Comment by mlugg** [comment]
@jiacai2050 I have a system set up to check every mirror twice a day, and I occasionally (every few weeks) get a notification that this mirror is encountering issues. The test in question is to try and download the latest `master` build. The last failure I had was at 2024/11/01 06:09 GMT+0; the GET request returned `{"status":1,"request":"8154ff6f-0542-4c16-9283-ec3eb825e730"}`. Are you able to look into this?

**Comment by jiacai2050** [comment]
I'm afraid this is not what my mirror returns, it's output of this line:
```sh
curl -s \
    -F user="$PUSHOVER_USER" -F token="$PUSHOVER_TOKEN" \
    -F message="Zig download mirror '$mirror_name' is down" \
    https://api.pushover.net/1/messages.json
```

And I recheck the function code, it will only cache missing zip file after get from upstream successfully.

Since it's running in cloudflare page function, I don't have more log to dig deeply...

**Comment by mlugg** [comment]
Oops, my bad, I misread the Action output!

I'll see if I can get you any more information when I next see a failure.

**Comment by jiacai2050** [comment]
OK

**Comment by Techatrix** [comment]
I have noticed some things about this mirror: 
- the http response headers does not include `content-length` which would be nice to have so that tools can report the download progress.
- requesting a file that doesn't exist will report 500 instead of 404 as the status code (exampe: [zig-windows-x86_64-0.20.0.zip](https://fs.liujiacai.net/zigbuilds/zig-windows-x86_64-0.20.0.zip)) Not all mirrors provide the same files so it's hard to differentiate whether the mirror is broken or just missing the file

This doesn't violate any of the requirements of a mirror so feel free to ignore but it would still be nice if this could be addressed.

**Comment by mlugg** [comment]
While it's nice QOL, I'm not too worried about the `Content-Length` header. However, I agree that the mirror shouldn't be returning status 500 for invalid accesses. @jiacai2050, could you look into that? If you can set it up to provide a `Content-Length` too that would be great, but it's alright if not.

I'll amend the rules to cover the status code issue when I get a chance. It seems reasonable to me that no request should *ever* respond with status 500 in normal operation; @Techatrix, would you agree?

**Comment by Techatrix** [comment]
> @Techatrix, would you agree?

Yes, I can't think of any situation where 500 would make sense.

**Comment by jiacai2050** [comment]
Those are reasonable improvements, I will fix them this week.

**Comment by jiacai2050** [comment]
```
$ curl -I https://fs.liujiacai.net/zigbuilds/zig-windows-x86_64-0.20.0.zip
HTTP/2 404 
date: Sat, 23 Nov 2024 03:47:31 GMT
content-type: text/html
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=Oh8zd2kxe71nitLajIxBStBu6FjiSW2Zh1aSJHEDiFRD3%2FDG4JXiiue%2FfKCmdReysoScnLSFu3qAae0L7Zk3zpqmRmV5lYL4momslKcG8Vnz3kYwqiYJsT9VUkt6veowZOEJ"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
vary: Accept-Encoding
cache-control: max-age=14400
cf-cache-status: MISS
server: cloudflare
cf-ray: 8e6e2d9c98aec4f1-SEA
alt-svc: h3=":443"; ma=86400
server-timing: cfL4;desc="?proto=TCP&rtt=184964&sent=6&recv=11&lost=0&retrans=0&sent_bytes=2885&recv_bytes=605&delivery_rate=15693&cwnd=251&unsent_bytes=0&cid=be150abd4e69bf59&ts=1913&x=0"
```

My mirror return 404 for non-existing files now.

But still no content-length header, since it's a chunked response.

**Comment by mlugg** [comment]
@jiacai2050 I just had one of the periodic issues with your mirror. After playing around, I think the issue is simply that your mirror is incredibly slow to download from when it hasn't fetched a file before. For instance, I just tried fetching `https://fs.liujiacai.net/zigbuilds/zig-linux-powerpc64le-0.14.0-dev.2645+affe45b31.tar.xz` for presumably the first time (nobody's really using powerpc lol), and fetching this 46 MiB archive took 47 seconds. Of those, *no data was received* for the the first 40 seconds -- presumably this time was spent on your mirror pulling from ziglang.org.

This is too slow; a download of a typical tarball can't take almost a minute in any case. Please see if you're able to improve the speed at which your mirror downloads from ziglang.org; otherwise, I'll have to remove it. I'm not sure why that route in particular is so slow, since downloading a tarball with a warmed-up cache (i.e. one which has been fetched before) can easily push around 6 MiB/s to my local network (and the limitation at that point is probably *my* network).

**Comment by jiacai2050** [comment]
Hi, an improvement has been implemented. For cases of cache misses, I now [defer caching](https://developers.cloudflare.com/workers/runtime-apis/context/#waituntil). This ensures that the response is returned promptly as possible.

In my local testing, I managed to reduce the response time by approximately half. 

Please check it again.

**Pull request merged**
